/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ClienteDashboardRouteImport } from './routes/cliente.dashboard'
import { Route as EmpleadoDashboardRouteImport } from './routes/empleado.dashboard'
import { Route as ProveedorDashboardRouteImport } from './routes/proveedor.dashboard'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos.index'
import { Route as ProyectosSlugRouteImport } from './routes/proyectos.$slug'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteDashboardRoute = ClienteDashboardRouteImport.update({
  id: '/cliente/dashboard',
  path: '/cliente/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleadoDashboardRoute = EmpleadoDashboardRouteImport.update({
  id: '/empleado/dashboard',
  path: '/empleado/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedorDashboardRoute = ProveedorDashboardRouteImport.update({
  id: '/proveedor/dashboard',
  path: '/proveedor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosSlugRoute = ProyectosSlugRouteImport.update({
  id: '/proyectos/$slug',
  path: '/proyectos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/empleado/dashboard': typeof EmpleadoDashboardRoute
  '/proveedor/dashboard': typeof ProveedorDashboardRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/empleado/dashboard': typeof EmpleadoDashboardRoute
  '/proveedor/dashboard': typeof ProveedorDashboardRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/proyectos': typeof ProyectosIndexRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/empleado/dashboard': typeof EmpleadoDashboardRoute
  '/proveedor/dashboard': typeof ProveedorDashboardRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/login'
    | '/registro'
    | '/sobre-nosotros'
    | '/style-guide'
    | '/admin/dashboard'
    | '/blog/$slug'
    | '/cliente/dashboard'
    | '/empleado/dashboard'
    | '/proveedor/dashboard'
    | '/proyectos/$slug'
    | '/servicios/$slug'
    | '/blog/'
    | '/proyectos/'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/login'
    | '/registro'
    | '/sobre-nosotros'
    | '/style-guide'
    | '/admin/dashboard'
    | '/blog/$slug'
    | '/cliente/dashboard'
    | '/empleado/dashboard'
    | '/proveedor/dashboard'
    | '/proyectos/$slug'
    | '/servicios/$slug'
    | '/blog'
    | '/proyectos'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/login'
    | '/registro'
    | '/sobre-nosotros'
    | '/style-guide'
    | '/admin/dashboard'
    | '/blog/$slug'
    | '/cliente/dashboard'
    | '/empleado/dashboard'
    | '/proveedor/dashboard'
    | '/proyectos/$slug'
    | '/servicios/$slug'
    | '/blog/'
    | '/proyectos/'
    | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  StyleGuideRoute: typeof StyleGuideRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ClienteDashboardRoute: typeof ClienteDashboardRoute
  EmpleadoDashboardRoute: typeof EmpleadoDashboardRoute
  ProveedorDashboardRoute: typeof ProveedorDashboardRoute
  ProyectosSlugRoute: typeof ProyectosSlugRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/dashboard': {
      id: '/cliente/dashboard'
      path: '/cliente/dashboard'
      fullPath: '/cliente/dashboard'
      preLoaderRoute: typeof ClienteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleado/dashboard': {
      id: '/empleado/dashboard'
      path: '/empleado/dashboard'
      fullPath: '/empleado/dashboard'
      preLoaderRoute: typeof EmpleadoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedor/dashboard': {
      id: '/proveedor/dashboard'
      path: '/proveedor/dashboard'
      fullPath: '/proveedor/dashboard'
      preLoaderRoute: typeof ProveedorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$slug': {
      id: '/proyectos/$slug'
      path: '/proyectos/$slug'
      fullPath: '/proyectos/$slug'
      preLoaderRoute: typeof ProyectosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  StyleGuideRoute: StyleGuideRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BlogSlugRoute: BlogSlugRoute,
  ClienteDashboardRoute: ClienteDashboardRoute,
  EmpleadoDashboardRoute: EmpleadoDashboardRoute,
  ProveedorDashboardRoute: ProveedorDashboardRoute,
  ProyectosSlugRoute: ProyectosSlugRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
