/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as RecuperarContrasenaRouteImport } from './routes/recuperar-contrasena'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCitasRouteImport } from './routes/admin.citas'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminMetricasRouteImport } from './routes/admin.metricas'
import { Route as AdminSolicitudesRouteImport } from './routes/admin.solicitudes'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ClienteDashboardRouteImport } from './routes/cliente.dashboard'
import { Route as EmpleadoDashboardRouteImport } from './routes/empleado.dashboard'
import { Route as ProveedorDashboardRouteImport } from './routes/proveedor.dashboard'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos.index'
import { Route as ProyectosSlugRouteImport } from './routes/proyectos.$slug'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'
import { Route as AdminEquipoIndexRouteImport } from './routes/admin.equipo.index'
import { Route as AdminEquipoNuevoRouteImport } from './routes/admin.equipo.nuevo'
import { Route as AdminProveedoresIndexRouteImport } from './routes/admin.proveedores.index'
import { Route as AdminProveedoresNuevoRouteImport } from './routes/admin.proveedores.nuevo'
import { Route as AdminProyectosIndexRouteImport } from './routes/admin.proyectos.index'
import { Route as AdminProyectosNuevoRouteImport } from './routes/admin.proyectos.nuevo'
import { Route as AdminServiciosIndexRouteImport } from './routes/admin.servicios.index'
import { Route as AdminServiciosNuevoRouteImport } from './routes/admin.servicios.nuevo'
import { Route as AdminTestimoniosIndexRouteImport } from './routes/admin.testimonios.index'
import { Route as AdminTestimoniosNuevoRouteImport } from './routes/admin.testimonios.nuevo'
import { Route as AdminEquipoIdEditarRouteImport } from './routes/admin.equipo.$id.editar'
import { Route as AdminProveedoresIdEditarRouteImport } from './routes/admin.proveedores.$id.editar'
import { Route as AdminProyectosIdEditarRouteImport } from './routes/admin.proyectos.$id.editar'
import { Route as AdminServiciosIdEditarRouteImport } from './routes/admin.servicios.$id.editar'
import { Route as AdminTestimoniosIdEditarRouteImport } from './routes/admin.testimonios.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarContrasenaRoute = RecuperarContrasenaRouteImport.update({
  id: '/recuperar-contrasena',
  path: '/recuperar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitasRoute = AdminCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricasRoute = AdminMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitudesRoute = AdminSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteDashboardRoute = ClienteDashboardRouteImport.update({
  id: '/cliente/dashboard',
  path: '/cliente/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleadoDashboardRoute = EmpleadoDashboardRouteImport.update({
  id: '/empleado/dashboard',
  path: '/empleado/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedorDashboardRoute = ProveedorDashboardRouteImport.update({
  id: '/proveedor/dashboard',
  path: '/proveedor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosSlugRoute = ProyectosSlugRouteImport.update({
  id: '/proyectos/$slug',
  path: '/proyectos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEquipoIndexRoute = AdminEquipoIndexRouteImport.update({
  id: '/equipo/',
  path: '/equipo/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipoNuevoRoute = AdminEquipoNuevoRouteImport.update({
  id: '/equipo/nuevo',
  path: '/equipo/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProveedoresIndexRoute = AdminProveedoresIndexRouteImport.update({
  id: '/proveedores/',
  path: '/proveedores/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProveedoresNuevoRoute = AdminProveedoresNuevoRouteImport.update({
  id: '/proveedores/nuevo',
  path: '/proveedores/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProyectosIndexRoute = AdminProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProyectosNuevoRoute = AdminProyectosNuevoRouteImport.update({
  id: '/proyectos/nuevo',
  path: '/proyectos/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiciosIndexRoute = AdminServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiciosNuevoRoute = AdminServiciosNuevoRouteImport.update({
  id: '/servicios/nuevo',
  path: '/servicios/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimoniosIndexRoute = AdminTestimoniosIndexRouteImport.update({
  id: '/testimonios/',
  path: '/testimonios/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimoniosNuevoRoute = AdminTestimoniosNuevoRouteImport.update({
  id: '/testimonios/nuevo',
  path: '/testimonios/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipoIdEditarRoute = AdminEquipoIdEditarRouteImport.update({
  id: '/equipo/$id/editar',
  path: '/equipo/$id/editar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProveedoresIdEditarRoute =
  AdminProveedoresIdEditarRouteImport.update({
    id: '/proveedores/$id/editar',
    path: '/proveedores/$id/editar',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProyectosIdEditarRoute = AdminProyectosIdEditarRouteImport.update({
  id: '/proyectos/$id/editar',
  path: '/proyectos/$id/editar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiciosIdEditarRoute = AdminServiciosIdEditarRouteImport.update({
  id: '/servicios/$id/editar',
  path: '/servicios/$id/editar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimoniosIdEditarRoute =
  AdminTestimoniosIdEditarRouteImport.update({
    id: '/testimonios/$id/editar',
    path: '/testimonios/$id/editar',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/reservar': typeof ReservarRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/citas': typeof AdminCitasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/empleado/dashboard': typeof EmpleadoDashboardRoute
  '/proveedor/dashboard': typeof ProveedorDashboardRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/admin/equipo/nuevo': typeof AdminEquipoNuevoRoute
  '/admin/proveedores/nuevo': typeof AdminProveedoresNuevoRoute
  '/admin/proyectos/nuevo': typeof AdminProyectosNuevoRoute
  '/admin/servicios/nuevo': typeof AdminServiciosNuevoRoute
  '/admin/testimonios/nuevo': typeof AdminTestimoniosNuevoRoute
  '/admin/equipo/': typeof AdminEquipoIndexRoute
  '/admin/proveedores/': typeof AdminProveedoresIndexRoute
  '/admin/proyectos/': typeof AdminProyectosIndexRoute
  '/admin/servicios/': typeof AdminServiciosIndexRoute
  '/admin/testimonios/': typeof AdminTestimoniosIndexRoute
  '/admin/equipo/$id/editar': typeof AdminEquipoIdEditarRoute
  '/admin/proveedores/$id/editar': typeof AdminProveedoresIdEditarRoute
  '/admin/proyectos/$id/editar': typeof AdminProyectosIdEditarRoute
  '/admin/servicios/$id/editar': typeof AdminServiciosIdEditarRoute
  '/admin/testimonios/$id/editar': typeof AdminTestimoniosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/reservar': typeof ReservarRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/citas': typeof AdminCitasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/empleado/dashboard': typeof EmpleadoDashboardRoute
  '/proveedor/dashboard': typeof ProveedorDashboardRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/proyectos': typeof ProyectosIndexRoute
  '/servicios': typeof ServiciosIndexRoute
  '/admin/equipo/nuevo': typeof AdminEquipoNuevoRoute
  '/admin/proveedores/nuevo': typeof AdminProveedoresNuevoRoute
  '/admin/proyectos/nuevo': typeof AdminProyectosNuevoRoute
  '/admin/servicios/nuevo': typeof AdminServiciosNuevoRoute
  '/admin/testimonios/nuevo': typeof AdminTestimoniosNuevoRoute
  '/admin/equipo': typeof AdminEquipoIndexRoute
  '/admin/proveedores': typeof AdminProveedoresIndexRoute
  '/admin/proyectos': typeof AdminProyectosIndexRoute
  '/admin/servicios': typeof AdminServiciosIndexRoute
  '/admin/testimonios': typeof AdminTestimoniosIndexRoute
  '/admin/equipo/$id/editar': typeof AdminEquipoIdEditarRoute
  '/admin/proveedores/$id/editar': typeof AdminProveedoresIdEditarRoute
  '/admin/proyectos/$id/editar': typeof AdminProyectosIdEditarRoute
  '/admin/servicios/$id/editar': typeof AdminServiciosIdEditarRoute
  '/admin/testimonios/$id/editar': typeof AdminTestimoniosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/reservar': typeof ReservarRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/citas': typeof AdminCitasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/solicitudes': typeof AdminSolicitudesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/empleado/dashboard': typeof EmpleadoDashboardRoute
  '/proveedor/dashboard': typeof ProveedorDashboardRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/admin/equipo/nuevo': typeof AdminEquipoNuevoRoute
  '/admin/proveedores/nuevo': typeof AdminProveedoresNuevoRoute
  '/admin/proyectos/nuevo': typeof AdminProyectosNuevoRoute
  '/admin/servicios/nuevo': typeof AdminServiciosNuevoRoute
  '/admin/testimonios/nuevo': typeof AdminTestimoniosNuevoRoute
  '/admin/equipo/': typeof AdminEquipoIndexRoute
  '/admin/proveedores/': typeof AdminProveedoresIndexRoute
  '/admin/proyectos/': typeof AdminProyectosIndexRoute
  '/admin/servicios/': typeof AdminServiciosIndexRoute
  '/admin/testimonios/': typeof AdminTestimoniosIndexRoute
  '/admin/equipo/$id/editar': typeof AdminEquipoIdEditarRoute
  '/admin/proveedores/$id/editar': typeof AdminProveedoresIdEditarRoute
  '/admin/proyectos/$id/editar': typeof AdminProyectosIdEditarRoute
  '/admin/servicios/$id/editar': typeof AdminServiciosIdEditarRoute
  '/admin/testimonios/$id/editar': typeof AdminTestimoniosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aviso-legal'
    | '/contacto'
    | '/login'
    | '/politica-privacidad'
    | '/recuperar-contrasena'
    | '/registro'
    | '/reservar'
    | '/restablecer-contrasena'
    | '/sobre-nosotros'
    | '/style-guide'
    | '/admin/citas'
    | '/admin/dashboard'
    | '/admin/metricas'
    | '/admin/solicitudes'
    | '/blog/$slug'
    | '/cliente/dashboard'
    | '/empleado/dashboard'
    | '/proveedor/dashboard'
    | '/proyectos/$slug'
    | '/servicios/$slug'
    | '/admin/'
    | '/blog/'
    | '/proyectos/'
    | '/servicios/'
    | '/admin/equipo/nuevo'
    | '/admin/proveedores/nuevo'
    | '/admin/proyectos/nuevo'
    | '/admin/servicios/nuevo'
    | '/admin/testimonios/nuevo'
    | '/admin/equipo/'
    | '/admin/proveedores/'
    | '/admin/proyectos/'
    | '/admin/servicios/'
    | '/admin/testimonios/'
    | '/admin/equipo/$id/editar'
    | '/admin/proveedores/$id/editar'
    | '/admin/proyectos/$id/editar'
    | '/admin/servicios/$id/editar'
    | '/admin/testimonios/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/login'
    | '/politica-privacidad'
    | '/recuperar-contrasena'
    | '/registro'
    | '/reservar'
    | '/restablecer-contrasena'
    | '/sobre-nosotros'
    | '/style-guide'
    | '/admin/citas'
    | '/admin/dashboard'
    | '/admin/metricas'
    | '/admin/solicitudes'
    | '/blog/$slug'
    | '/cliente/dashboard'
    | '/empleado/dashboard'
    | '/proveedor/dashboard'
    | '/proyectos/$slug'
    | '/servicios/$slug'
    | '/admin'
    | '/blog'
    | '/proyectos'
    | '/servicios'
    | '/admin/equipo/nuevo'
    | '/admin/proveedores/nuevo'
    | '/admin/proyectos/nuevo'
    | '/admin/servicios/nuevo'
    | '/admin/testimonios/nuevo'
    | '/admin/equipo'
    | '/admin/proveedores'
    | '/admin/proyectos'
    | '/admin/servicios'
    | '/admin/testimonios'
    | '/admin/equipo/$id/editar'
    | '/admin/proveedores/$id/editar'
    | '/admin/proyectos/$id/editar'
    | '/admin/servicios/$id/editar'
    | '/admin/testimonios/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aviso-legal'
    | '/contacto'
    | '/login'
    | '/politica-privacidad'
    | '/recuperar-contrasena'
    | '/registro'
    | '/reservar'
    | '/restablecer-contrasena'
    | '/sobre-nosotros'
    | '/style-guide'
    | '/admin/citas'
    | '/admin/dashboard'
    | '/admin/metricas'
    | '/admin/solicitudes'
    | '/blog/$slug'
    | '/cliente/dashboard'
    | '/empleado/dashboard'
    | '/proveedor/dashboard'
    | '/proyectos/$slug'
    | '/servicios/$slug'
    | '/admin/'
    | '/blog/'
    | '/proyectos/'
    | '/servicios/'
    | '/admin/equipo/nuevo'
    | '/admin/proveedores/nuevo'
    | '/admin/proyectos/nuevo'
    | '/admin/servicios/nuevo'
    | '/admin/testimonios/nuevo'
    | '/admin/equipo/'
    | '/admin/proveedores/'
    | '/admin/proyectos/'
    | '/admin/servicios/'
    | '/admin/testimonios/'
    | '/admin/equipo/$id/editar'
    | '/admin/proveedores/$id/editar'
    | '/admin/proyectos/$id/editar'
    | '/admin/servicios/$id/editar'
    | '/admin/testimonios/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvisoLegalRoute: typeof AvisoLegalRoute
  ContactoRoute: typeof ContactoRoute
  LoginRoute: typeof LoginRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  RecuperarContrasenaRoute: typeof RecuperarContrasenaRoute
  RegistroRoute: typeof RegistroRoute
  ReservarRoute: typeof ReservarRoute
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  StyleGuideRoute: typeof StyleGuideRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ClienteDashboardRoute: typeof ClienteDashboardRoute
  EmpleadoDashboardRoute: typeof EmpleadoDashboardRoute
  ProveedorDashboardRoute: typeof ProveedorDashboardRoute
  ProyectosSlugRoute: typeof ProyectosSlugRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-contrasena': {
      id: '/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof RecuperarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/citas': {
      id: '/admin/citas'
      path: '/citas'
      fullPath: '/admin/citas'
      preLoaderRoute: typeof AdminCitasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metricas': {
      id: '/admin/metricas'
      path: '/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AdminMetricasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitudes': {
      id: '/admin/solicitudes'
      path: '/solicitudes'
      fullPath: '/admin/solicitudes'
      preLoaderRoute: typeof AdminSolicitudesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/dashboard': {
      id: '/cliente/dashboard'
      path: '/cliente/dashboard'
      fullPath: '/cliente/dashboard'
      preLoaderRoute: typeof ClienteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleado/dashboard': {
      id: '/empleado/dashboard'
      path: '/empleado/dashboard'
      fullPath: '/empleado/dashboard'
      preLoaderRoute: typeof EmpleadoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedor/dashboard': {
      id: '/proveedor/dashboard'
      path: '/proveedor/dashboard'
      fullPath: '/proveedor/dashboard'
      preLoaderRoute: typeof ProveedorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$slug': {
      id: '/proyectos/$slug'
      path: '/proyectos/$slug'
      fullPath: '/proyectos/$slug'
      preLoaderRoute: typeof ProyectosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/equipo/': {
      id: '/admin/equipo/'
      path: '/equipo'
      fullPath: '/admin/equipo/'
      preLoaderRoute: typeof AdminEquipoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipo/nuevo': {
      id: '/admin/equipo/nuevo'
      path: '/equipo/nuevo'
      fullPath: '/admin/equipo/nuevo'
      preLoaderRoute: typeof AdminEquipoNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proveedores/': {
      id: '/admin/proveedores/'
      path: '/proveedores'
      fullPath: '/admin/proveedores/'
      preLoaderRoute: typeof AdminProveedoresIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proveedores/nuevo': {
      id: '/admin/proveedores/nuevo'
      path: '/proveedores/nuevo'
      fullPath: '/admin/proveedores/nuevo'
      preLoaderRoute: typeof AdminProveedoresNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proyectos/': {
      id: '/admin/proyectos/'
      path: '/proyectos'
      fullPath: '/admin/proyectos/'
      preLoaderRoute: typeof AdminProyectosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proyectos/nuevo': {
      id: '/admin/proyectos/nuevo'
      path: '/proyectos/nuevo'
      fullPath: '/admin/proyectos/nuevo'
      preLoaderRoute: typeof AdminProyectosNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicios/': {
      id: '/admin/servicios/'
      path: '/servicios'
      fullPath: '/admin/servicios/'
      preLoaderRoute: typeof AdminServiciosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicios/nuevo': {
      id: '/admin/servicios/nuevo'
      path: '/servicios/nuevo'
      fullPath: '/admin/servicios/nuevo'
      preLoaderRoute: typeof AdminServiciosNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonios/': {
      id: '/admin/testimonios/'
      path: '/testimonios'
      fullPath: '/admin/testimonios/'
      preLoaderRoute: typeof AdminTestimoniosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonios/nuevo': {
      id: '/admin/testimonios/nuevo'
      path: '/testimonios/nuevo'
      fullPath: '/admin/testimonios/nuevo'
      preLoaderRoute: typeof AdminTestimoniosNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipo/$id/editar': {
      id: '/admin/equipo/$id/editar'
      path: '/equipo/$id/editar'
      fullPath: '/admin/equipo/$id/editar'
      preLoaderRoute: typeof AdminEquipoIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proveedores/$id/editar': {
      id: '/admin/proveedores/$id/editar'
      path: '/proveedores/$id/editar'
      fullPath: '/admin/proveedores/$id/editar'
      preLoaderRoute: typeof AdminProveedoresIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proyectos/$id/editar': {
      id: '/admin/proyectos/$id/editar'
      path: '/proyectos/$id/editar'
      fullPath: '/admin/proyectos/$id/editar'
      preLoaderRoute: typeof AdminProyectosIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicios/$id/editar': {
      id: '/admin/servicios/$id/editar'
      path: '/servicios/$id/editar'
      fullPath: '/admin/servicios/$id/editar'
      preLoaderRoute: typeof AdminServiciosIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonios/$id/editar': {
      id: '/admin/testimonios/$id/editar'
      path: '/testimonios/$id/editar'
      fullPath: '/admin/testimonios/$id/editar'
      preLoaderRoute: typeof AdminTestimoniosIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCitasRoute: typeof AdminCitasRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMetricasRoute: typeof AdminMetricasRoute
  AdminSolicitudesRoute: typeof AdminSolicitudesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEquipoNuevoRoute: typeof AdminEquipoNuevoRoute
  AdminProveedoresNuevoRoute: typeof AdminProveedoresNuevoRoute
  AdminProyectosNuevoRoute: typeof AdminProyectosNuevoRoute
  AdminServiciosNuevoRoute: typeof AdminServiciosNuevoRoute
  AdminTestimoniosNuevoRoute: typeof AdminTestimoniosNuevoRoute
  AdminEquipoIndexRoute: typeof AdminEquipoIndexRoute
  AdminProveedoresIndexRoute: typeof AdminProveedoresIndexRoute
  AdminProyectosIndexRoute: typeof AdminProyectosIndexRoute
  AdminServiciosIndexRoute: typeof AdminServiciosIndexRoute
  AdminTestimoniosIndexRoute: typeof AdminTestimoniosIndexRoute
  AdminEquipoIdEditarRoute: typeof AdminEquipoIdEditarRoute
  AdminProveedoresIdEditarRoute: typeof AdminProveedoresIdEditarRoute
  AdminProyectosIdEditarRoute: typeof AdminProyectosIdEditarRoute
  AdminServiciosIdEditarRoute: typeof AdminServiciosIdEditarRoute
  AdminTestimoniosIdEditarRoute: typeof AdminTestimoniosIdEditarRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCitasRoute: AdminCitasRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMetricasRoute: AdminMetricasRoute,
  AdminSolicitudesRoute: AdminSolicitudesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEquipoNuevoRoute: AdminEquipoNuevoRoute,
  AdminProveedoresNuevoRoute: AdminProveedoresNuevoRoute,
  AdminProyectosNuevoRoute: AdminProyectosNuevoRoute,
  AdminServiciosNuevoRoute: AdminServiciosNuevoRoute,
  AdminTestimoniosNuevoRoute: AdminTestimoniosNuevoRoute,
  AdminEquipoIndexRoute: AdminEquipoIndexRoute,
  AdminProveedoresIndexRoute: AdminProveedoresIndexRoute,
  AdminProyectosIndexRoute: AdminProyectosIndexRoute,
  AdminServiciosIndexRoute: AdminServiciosIndexRoute,
  AdminTestimoniosIndexRoute: AdminTestimoniosIndexRoute,
  AdminEquipoIdEditarRoute: AdminEquipoIdEditarRoute,
  AdminProveedoresIdEditarRoute: AdminProveedoresIdEditarRoute,
  AdminProyectosIdEditarRoute: AdminProyectosIdEditarRoute,
  AdminServiciosIdEditarRoute: AdminServiciosIdEditarRoute,
  AdminTestimoniosIdEditarRoute: AdminTestimoniosIdEditarRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvisoLegalRoute: AvisoLegalRoute,
  ContactoRoute: ContactoRoute,
  LoginRoute: LoginRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  RecuperarContrasenaRoute: RecuperarContrasenaRoute,
  RegistroRoute: RegistroRoute,
  ReservarRoute: ReservarRoute,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  StyleGuideRoute: StyleGuideRoute,
  BlogSlugRoute: BlogSlugRoute,
  ClienteDashboardRoute: ClienteDashboardRoute,
  EmpleadoDashboardRoute: EmpleadoDashboardRoute,
  ProveedorDashboardRoute: ProveedorDashboardRoute,
  ProyectosSlugRoute: ProyectosSlugRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
